// this file contains product constants

export const PRODUCT_LIST_REQUEST = "PROCUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PROCUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PROCUCT_LIST_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PROCUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PROCUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PROCUCT_DETAILS_FAIL";
